- hosts: localhost
  tasks: 
    - name: installing git
      yum:
        name: git
        state: latest
      become: yes
      become_method: sudo
    - name: cloning petclinic
      git:
        repo: https://github.com/eamram/spring-petclinic.git
        dest: /home/ec2-user/petclinic 
      become: yes
      become_method: sudo
    - name: cloning tocd
      git:
        repo: https://github.com/eamram/tocd.git
        dest: /home/ec2-user/tocd
        update: no
      become: yes
      become_method: sudo
    - name: installing docker
      yum:
        name: docker
        state: latest
      become: yes
      become_method: sudo
    - name: add group docker to ec2-user
      user:
        name: ec2-user
        groups: docker
        append: yes
      become: yes
      become_method: sudo
    - name: start Docker service
      service:
        name: docker
        state: started
      become: yes
      become_method: sudo
